name: Delete Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Enter the branch name to delete"
        required: true

jobs:
  delete_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Delete the Branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # Reference your PAT secret
        run: |
          git push origin --delete ${{ github.event.inputs.branch_name }}  # Deletes remote branch

      - name: Confirm branch deletion
        run: echo "Branch ${{ github.event.inputs.branch_name }} deleted successfully!"
