name: Rename Branch

on:
  workflow_dispatch:
    inputs:
      old_branch_name:
        description: "Enter the current branch name to rename"
        required: true
      new_branch_name:
        description: "Enter the new branch name"
        required: true

jobs:
  rename_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rename the Branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git checkout ${{ github.event.inputs.old_branch_name }} # Checkout to the old branch
          git branch -m ${{ github.event.inputs.new_branch_name }} # Rename the branch locally
          git push origin :${{ github.event.inputs.old_branch_name }} # Delete the old branch from the remote
          git push origin ${{ github.event.inputs.new_branch_name }} # Push the new branch to the remote

      - name: Confirm branch renaming
        run: echo "Branch renamed from ${{ github.event.inputs.old_branch_name }} to ${{ github.event.inputs.new_branch_name }} successfully!"
