name: Rename Branch

on:
  workflow_dispatch:
    inputs:
      old_branch_name:
        description: "Enter the old branch name"
        required: true
      new_branch_name:
        description: "Enter new branch name"
        required: true

jobs:
  update_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Config Git
        run: /
          git config user.name "github-actions[bot]"
          git config user.email "gihub-actions[bot]@users.noreply.github.com"

      - name: Rename the Branch
        env:
          PAT_TOKEN: ${{secrets.PAT_TOKEN}}
        run: 
          git chechout ${{github.event.inputs.old_branch_name}}
          git branch -m ${{github.event.inputs.new_branch_name}}
          git push origin :${{github.event.inputs.old_branch_name}}
          git push origin ${{github.event.inputs.new_branch_name}}
      
      - name: Rename Branch name
        run: echo "Branch ${{ github.event.inputs.branch_name }} rename successfully!"
